### ISSUE TITLE
Cannot export time-varying background values to .csv file when IRF is loaded

### ISSUE THREAD

**Issue by WenjunGuo2015** [imperial-photonics/FLIMfit#149]

**Comment by imunro** [comment]
Hi Wenjun. I just tried to  replicate this and it looked ok. Can you give me more details please and perhaps some test data. Thanks.

**Comment by WenjunGuo2015** [comment]
Hi Ian, thanks for the reply. I've tried again by loading a single image and a spatially varying IRF and then exporting the values of the data points, yet still no .csv file can be generated. Maybe the difference is that I have used a spatially varying IRF? Attached below is the error message:
![untitled](https://cloud.githubusercontent.com/assets/10564404/8854841/f520f794-3159-11e5-9923-81e05c5a4f4a.png)
I am not sure if I am describing the issue clear enough. If not, could we meet in your office some time next Wednesday afternoon?
Cheers!

**Comment by imunro** [comment]
Thanks Wenjun I'll have another try with a spatially varying irf.

Ian

**Comment by imunro** [comment]
Sorry Wenjun I failed again to replicate this . I think you need to take me through your workflow. When are you next around?

**Comment by imunro** [comment]
Looking again at this is it possible that there are different Nos of time points in the irf and the decay ?
Can you give me access to the data that is giving you the problem ?

**Comment by WenjunGuo2015** [comment]
Hi Ian. Yes I think it could be due to that the Nos of time points are different in the IRF and the decay. I will send you my data and IRF via email right away. Thanks a lot.

**Comment by imunro** [comment]
Hi Wenjun. Still not getting this: I have no idea what to do with the irf shift map file. Can we go through it on Wed as you originally suggested ?

**Comment by WenjunGuo2015** [comment]
No problem. Thanks a lot for working on this issue. I will go through it with you this Wed afternoon, say, after the journal club?

**Comment by imunro** [comment]
Perfect. See you then.

**Comment by imunro** [comment]
Thanks for taking me through this Wenjun. The issue seems to be when you import a shift map using "Load Spatially Varying irf" as you demonstrated then the irf data seems to be transposed (i.e. a row rather than a column). So @seanwarren can I ask if this is a valid thing to do?

**Comment by seanwarren** [comment]
This sounds like a bug - I think we need a check to ensure the correct matrix orientation when the IRF is imported

Cheers
Sean

On 29 Jul 2015, at 23:47, imunro <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for taking me through this Wenjun. The issue seems to be when you import a shift map using "Load Spatially Varying irf" as you demonstrated then the irf data seems to be transposed (i.e. a row rather than a column). So @seanwarren<https://github.com/seanwarren> can I ask if this is a valid thing to do?

**Comment by imunro** [comment]
Because it's a .xml file there's an exception in the "Load Spatially Varying irf" that imports using marshal(object).I assume therefore that the problem lies earlier in the creation or export  of the shift map.  However nobody is reporting problems with the shift maps? 

One option is to add an "Import IRF shift map" menu item & as doing it via the "Spatially Varying irf" button seems a bit counter-intuitive to me.

**Comment by imunro** [comment]
"Sticking plaster" solution apparently works in 4.9.1 - needs further investigation to discover if Wenjun is generating malformed .xml files and if so why.

**Comment by seanwarren** [comment]
@WenjunGuo2015 , @imunro  is this still outstanding? some brief testing over here shows that this seems to be working as expected
