### ISSUE TITLE
Different fit results from Mac to Win7.

### ISSUE THREAD

**Issue by imunro** [imperial-photonics/FLIMfit#153]
Ross @ Beatson reports that he gets different results when fitting with the Windows and Mac  versions of FLIMfit.   Confirmed  using their data. Differences are not insignificant  e.g. tau = 4.9961 e+03 on Win7 vs 4.9657 e+03 on OSX.

**Comment by imunro** [comment]
So far I have confirmed (by exporting the data from a pixel) that both data and irf are the same on the 2 machines but residuals differ which implies that the problem lies in the c++.

**Comment by seanwarren** [comment]
This looks pretty bad - I’ll have a look ASAP.
Please can you send me the data you’re using to reproduce this


On 1 Aug 2015, at 04:38, imunro <notifications@github.com<mailto:notifications@github.com>> wrote:


So far I have confirmed (by exporting the data from a pixel) that both data and irf are the same on the 2 machines but residuals differ which implies that the problem lies in the c++.

**Comment by imunro** [comment]
All assistance welcome @seanwarren can you let me know your current e-mail address.

**Comment by imunro** [comment]
Addressed in 4.10.3 (I think) Prpbably attributed to rounding errors. @seanwarren cab you remember ?

**Comment by imunro** [comment]
@seanwarren do you think we can close this one ?

**Comment by imunro** [comment]
I think we attributed this to rounding errors in the end @seanwarren  close if you're happy.
