### ISSUE TITLE
Possible performance issues with uncompressed .sdt files.

### ISSUE THREAD

**Issue by imunro** [imperial-photonics/FLIMfit#157]
https://github.com/openmicroscopy/bioformats/pull/1950 adds the ability to load compressed .sdt files to bio-formats.(see https://github.com/openmicroscopy/Imperial-FLIMfit/issues/114 ) Note however my comments about possible unnecessary overhead of one 'if' per line. TBD Benchmark with new and old bio-formats. If there is significant slowdown then implement my suggested solution of overriding rather than using a function.

**Comment by seanwarren** [comment]
Hi Ian,

I imagine branch prediction should sort out most of those if statements.

On 27 Aug 2015 9:56 pm, imunro <notifications@github.com> wrote:

openmicroscopy/bioformats#1950<https://github.com/openmicroscopy/bioformats/pull/1950> adds the ability to load compressed .sdt files to bio-formats.(see #114<https://github.com/openmicroscopy/Imperial-FLIMfit/issues/114> ) Note however my comments about possible unnecessary overhead of one 'if' per line. TBD Benchmark with new and old bio-formats. If there is significant slowdown then implement my suggested solution of overriding rather than using a function.

**Comment by imunro** [comment]
Hi Sean - it may be that it's al I/O limited anyway but thought it's be good to check.

**Comment by imunro** [comment]
Nobody seems to be moaning - so let's assume it's "fast enough"
