### ISSUE TITLE
Implement options dialog to choose spatial binning and temporal resolution for FLIMreader

### ISSUE THREAD

**Issue by seanwarren** [imperial-photonics/FLIMfit#198]
Currently temporal resolution fixed such that there are 256 time bins

**Comment by seanwarren** [comment]
Implemented with merge of #199

**Comment by imunro** [comment]
@seanwarren this has currently broken the OMERO side completely.
The issue is that I overload flim_data_series.get_image_dimnesions and the interface no longer matches
as there's an extra reader_settings returned. Is there some "do whatever you used to do" values that  I can return in get_image dimensions?

**Comment by seanwarren** [comment]
Sorry about this @imunro - I've commit 2a69f6f84372f7e1c18bb4ec83bdfa406897e608 should address this. I can't test OMERO stuff here so could you try please?

**Comment by imunro** [comment]
Certainly and thanks. If you want to be able to test OMERO stuff I can easily get you an account on Dundee's demo server , which I use.. Just let me know. However I can quite see that you wouldn't want to.

**Comment by imunro** [comment]
Passed a quick fire test. I'll check more throughly later but looks good.
